# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocaopodSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '5.2'
  # Pods for CocaopodSample

  target 'CocaopodSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocaopodSampleUITests' do
    # Pods for testing
  end

end
